version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    # volumes:
    #   - /data/postgres:/data/postgres
    env_file:
      - docker.env

  docker_file:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: unless-stopped
    container_name: docker_file